version: '3'
services:
  web:
    build:
      context: ../../app
      dockerfile: Dockerfile.dev
    volumes:
      - ../../app:/usr/src/app
    hostname: web
    ports:
      - '3000:3000'
  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'