version: '3'
services:
  web:
    restart: on-failure
    build:
      context: ../../app
      dockerfile: Dockerfile.prod
    hostname: web
    ports:
      - '3000:3000'
  redis:
    image: redis
    hostname: redis
  test:
    build:
      context: ../../test
      dockerfile: Dockerfile
